### ISSUE TITLE
High level requirements

### ISSUE THREAD

**Issue by Danwhy** [TheScienceMuseum/360-image-uploader#1]
The Science museum have a number of 360 images that they need to keep track of in order to use on the Collections Online site. To facilitate this, we will need to provide a way for the images to be uploaded to AWS S3, keep track of those that have, and provide a record of the images to reference from Collections Online.

- [x] Host a html form using AWS S3/Lambda for uploading 360 images to S3
- [x] Lambda function to store 360 image details in DynamoDB
- [x] Lambda functions to list/delete 360 images
- [x] Lambda function to retrieve json representation of 360 images
